# backend/src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobtracker
    username: admin
    password: password123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: zhan      # 自定义用户名
      password: 123 # 自定义密码
  # Redis 配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}  # 支持环境变量，默认localhost
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

jwt:
  secret: "thisIsASuperSecureKeyWithMoreThan64Characters1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  expiration: 86400000  # 24小时（毫秒）

app:
  # 用于内部服务间通信的API密钥，请务必修改为一个长且随机的字符串
  internal-api-key: "thisisaramdomandVeryLongStringtoMakeItASecretKey155423asc5assajci,w,YAJCB"